import type { Receipt } from './order-receipt.js';

export type OrderEmail = Pick<Receipt, 'email' | 'customer' | 'items' | 'orderNumber' | 'total'> & { payment: 'online' | 'cod' };
export const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
export const money = (value: number) => `INR ${value.toFixed(2)}`;
export function orderMessage(order: OrderEmail) {
  const e = escapeHtml, customer = order.customer;
  const address = [customer.address, customer.city, customer.state, customer.pincode].filter(Boolean).join(', ');
  const cod = order.payment === 'cod';
  const payment = cod ? 'Cash on delivery — payment due on delivery' : 'Online payment confirmed';
  const totalLabel = cod ? 'Amount due on delivery' : 'Total paid';
  const rows = order.items.map(item => `<tr><td style="padding:16px 0;border-bottom:1px solid #e4d9ce;overflow-wrap:anywhere">${e(item.name)}<br/><small>Size ${e(item.size)}${item.color ? ` · ${e(item.color)}` : ''} · Qty ${item.qty}<br/>Unit price: ${money(item.price)}</small></td><td style="padding-left:12px;text-align:right;white-space:nowrap">${money(item.price * item.qty)}</td></tr>`).join('');
  const html = `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"/></head><body style="margin:0;background:#f7f3ed;color:#33291f;font-family:Arial,sans-serif"><table role="presentation" style="width:100%;max-width:620px;margin:0 auto;background:#fffdf9;border-collapse:collapse"><tr><td style="padding:28px 20px"><p style="font-weight:bold;letter-spacing:2px">FREE FIRE STORE</p><p style="font-size:12px;letter-spacing:2px;color:#786150">ORDER CONFIRMED</p><h1 style="font:32px Georgia,serif">Thank you for your order.</h1><p>Hi ${e(customer.firstName || 'there')}, your order has been received.${cod ? ' Please pay when your order arrives.' : ' Your payment is confirmed.'}</p><p><strong>Order #${e(order.orderNumber)}</strong></p>${rows ? `<table style="width:100%;border-collapse:collapse">${rows}</table>` : '<p>Your saved product details are available in My Orders.</p>'}<p style="font-size:19px"><strong>${totalLabel}: ${money(order.total)}</strong></p><p>${payment}<br/>Delivery: Free</p><h2 style="font:22px Georgia,serif">Customer & delivery details</h2><p style="line-height:1.8;overflow-wrap:anywhere">${e([customer.firstName, customer.lastName].filter(Boolean).join(' '))}<br/>${e(order.email)}<br/>${e(customer.phone)}<br/>${e(address)}</p><p style="line-height:1.7">View My Orders for your order details and available delivery updates.</p><hr style="border:0;border-top:1px solid #e4d9ce"/><p style="font-size:12px">Thank you for choosing Free Fire Store.</p></td></tr></table></body></html>`;
  const text = `Free Fire Store\nOrder #${order.orderNumber} confirmed\n${payment}\n${totalLabel}: ${money(order.total)}\nDelivery: Free\n${order.items.map(item => `${item.name} / Size ${item.size}${item.color ? ` / ${item.color}` : ''} / Qty ${item.qty} / Unit ${money(item.price)} / Total ${money(item.price * item.qty)}`).join('\n')}\nCustomer: ${customer.firstName} ${customer.lastName}\nEmail: ${order.email}\nPhone: ${customer.phone}\nDeliver to: ${address}\nView My Orders for available delivery updates.\nFree Fire Store`;
  return { subject: `Order #${order.orderNumber} confirmed — Free Fire Store`, html, text };
}
