import fs from 'fs';
import path from 'path';

const rawData = `Motion-reduce Image	Motion-reduce (2) Image	URL	Motion-reduce Description	Price	S	Discount-badge	Jdgm-prev-badge__text	Full-unstyled-link	Visually-hidden
https://deodap.in/cdn/shop/files/rboJ7tIwtn.jpg?v=1776775809	https://deodap.in/cdn/shop/files/6PKX9qfs1j.jpg?v=1776775809	https://deodap.in/products/premium-glossy-stainless-steel-wall-mounted-4-rod-towel-holder-rack-mc	Premium Glossy Stainless Steel Wall Mounted 4 Rod Towel Holder Rack	Rs. 424.00	Rs. 610.00	30% OFF	(10)	Premium Glossy Stainless Steel Wall Mounted 4 Rod...	Decrease quantity for Premium Glossy Stainless Steel Wall Mounted 4 Rod Towel Holder Rack
https://deodap.in/cdn/shop/files/GvTZO2FuNH.jpg?v=1776775809	https://deodap.in/cdn/shop/files/RM8O3VMlUU.jpg?v=1776776180	https://deodap.in/products/premium-stainless-steel-wall-mounted-bathroom-shelf-rack-organizer-qh	Premium Stainless Steel Wall Mounted Bathroom Shelf Rack Organizer	Rs. 349.00	Rs. 500.00	30% OFF	(10)	Premium Stainless Steel Wall Mounted Bathroom Shelf Rack...	Decrease quantity for Premium Stainless Steel Wall Mounted Bathroom Shelf Rack Organizer
https://deodap.in/cdn/shop/files/Q4Y0rBPW1N.jpg?v=1776690534	https://deodap.in/cdn/shop/files/jHE5ujtTca.jpg?v=1776690534	https://deodap.in/products/wall-mounted-bathroom-storage-shelf-with-integrated-towel-holder-rack	Wall-Mounted Bathroom Storage Shelf with Integrated Towel Holder Rack	Rs. 116.00	Rs. 499.00	76% OFF	No reviews	Wall-Mounted Bathroom Storage Shelf with Integrated Towel...	Decrease quantity for Wall-Mounted Bathroom Storage Shelf with Integrated Towel Holder Rack
https://deodap.in/cdn/shop/files/rd2f5yOE5f.jpg?v=1776689200	https://deodap.in/cdn/shop/files/vBuMljPDV6.jpg?v=1776689200	https://deodap.in/products/premium-square-dial-silver-metal-strap-analog-wrist-watch-for-men	Premium Square Dial Silver Metal Strap Analog Wrist Watch for Men	Rs. 290.00	Rs. 399.00	27% OFF	No reviews	Premium Square Dial Silver Metal Strap Analog Wrist...	Decrease quantity for Premium Square Dial Silver Metal Strap Analog Wrist Watch for Men
https://deodap.in/cdn/shop/files/3oPZnjEVPI.jpg?v=1776689200	https://deodap.in/cdn/shop/files/zOuGiOCaMJ.jpg?v=1776689200	https://deodap.in/products/premium-silver-analog-chronograph-style-wrist-watch-for-men	Premium Silver Analog Chronograph Style Wrist Watch for Men	Rs. 290.00	Rs. 399.00	27% OFF	No reviews	Premium Silver Analog Chronograph Style Wrist Watch for...	Decrease quantity for Premium Silver Analog Chronograph Style Wrist Watch for Men
https://deodap.in/cdn/shop/files/6EZ0WookX2.jpg?v=1776689200	https://deodap.in/cdn/shop/files/ja7aBr2biJ.jpg?v=1776689200	https://deodap.in/products/premium-black-analog-chronograph-style-wrist-watch-for-men	Premium Black Analog Chronograph Style Wrist Watch for Men	Rs. 305.00	Rs. 399.00	23% OFF	No reviews	Premium Black Analog Chronograph Style Wrist Watch for...	Decrease quantity for Premium Black Analog Chronograph Style Wrist Watch for Men
https://deodap.in/cdn/shop/files/TzsJzOLU2S.jpg?v=1776688334	https://deodap.in/cdn/shop/files/MpOmj7hraa.jpg?v=1776688334	https://deodap.in/products/matte-black-square-dial-metal-strap-analog-wrist-watch-for-men	Matte Black Square Dial Metal Strap Analog Wrist Watch for Men	Rs. 305.00	Rs. 399.00	23% OFF	No reviews	Matte Black Square Dial Metal Strap Analog Wrist...	Decrease quantity for Matte Black Square Dial Metal Strap Analog Wrist Watch for Men
https://deodap.in/cdn/shop/files/GgQELuCUPf.jpg?v=1776689200	https://deodap.in/cdn/shop/files/BiH0MPYyj9.jpg?v=1776689200	https://deodap.in/products/premium-square-dial-multi-function-analog-wrist-watch-with-stylish-stripe-fabric-leather-strap-for-men	Premium Square Dial Multi-Function Analog Wrist Watch with Stylish Stripe Fabric-Leather Strap for Men	Rs. 230.00	Rs. 399.00	42% OFF	No reviews	Premium Square Dial Multi-Function Analog Wrist Watch wit...	Decrease quantity for Premium Square Dial Multi-Function Analog Wrist Watch with Stylish Stripe Fabric-Leather Strap for Men
https://deodap.in/cdn/shop/files/utBaFSWpn6.jpg?v=1776688334	https://deodap.in/cdn/shop/files/ohSsD62UzO.jpg?v=1776688334	https://deodap.in/products/bold-black-multi-dial-chronograph-style-analog-wrist-watch-with-protective-crown-guard-leather-strap-for-men	Bold Black Multi-Dial Chronograph Style Analog Wrist Watch with Protective Crown Guard & Leather Strap for Men	Rs. 240.00	Rs. 399.00	39% OFF	No reviews	Bold Black Multi-Dial Chronograph Style Analog Wrist Watc...	Decrease quantity for Bold Black Multi-Dial Chronograph Style Analog Wrist Watch with Protective Crown Guard &amp; Leather Strap for Men
https://deodap.in/cdn/shop/files/3wYmBdchYh.jpg?v=1776688334	https://deodap.in/cdn/shop/files/rriuEWPZPx.jpg?v=1776689199	https://deodap.in/products/premium-octagonal-silver-dial-analog-wrist-watch-with-leather-strap-for-men	Premium Octagonal Silver Dial Analog Wrist Watch with Leather Strap for Men	Rs. 230.00	Rs. 399.00	42% OFF	No reviews	Premium Octagonal Silver Dial Analog Wrist Watch with...	Decrease quantity for Premium Octagonal Silver Dial Analog Wrist Watch with Leather Strap for Men
https://deodap.in/cdn/shop/files/60sV7oEXzA.jpg?v=1776689200	https://deodap.in/cdn/shop/files/UW1j2VHDie.jpg?v=1776689200	https://deodap.in/products/elegant-silver-dial-analog-wrist-watch-with-premium-textured-strap-for-men	Elegant Silver Dial Analog Wrist Watch with Premium Textured Strap for Men	Rs. 230.00	Rs. 399.00	42% OFF	No reviews	Elegant Silver Dial Analog Wrist Watch with Premium...	Decrease quantity for Elegant Silver Dial Analog Wrist Watch with Premium Textured Strap for Men
https://deodap.in/cdn/shop/files/Iv5W8DUJLn.jpg?v=1776689200	https://deodap.in/cdn/shop/files/l91XSaTis0.jpg?v=1776689200	https://deodap.in/products/premium-matte-black-octagonal-analog-wrist-watch-with-leather-strap-for-men	Premium Matte Black Octagonal Analog Wrist Watch with Leather Strap for Men	Rs. 240.00	Rs. 399.00	39% OFF	No reviews	Premium Matte Black Octagonal Analog Wrist Watch with...	Decrease quantity for Premium Matte Black Octagonal Analog Wrist Watch with Leather Strap for Men
https://deodap.in/cdn/shop/files/cOu4rjwbVU.jpg?v=1776684099	https://deodap.in/cdn/shop/files/VRd8UPLlM7.jpg?v=1776684099	https://deodap.in/products/wooden-photo-frame-lamp-with-led-crystal-globe-light	Wooden Photo Frame Lamp with LED Crystal Globe Light	Rs. 264.00	Rs. 528.00	50% OFF	No reviews	Wooden Photo Frame Lamp with LED Crystal Globe...	Decrease quantity for Wooden Photo Frame Lamp with LED Crystal Globe Light
https://deodap.in/cdn/shop/files/jsBkOsbYah.jpg?v=1776684099	https://deodap.in/cdn/shop/files/LtJlLaS6kE.jpg?v=1776684099	https://deodap.in/products/abstract-black-gold-panther-showpiece-decorative-home-statue	Abstract Black Gold Panther Showpiece Decorative Home Statue	Rs. 849.00	Rs. 1,698.00	50% OFF	No reviews	Abstract Black Gold Panther Showpiece Decorative Home Statue	Decrease quantity for Abstract Black Gold Panther Showpiece Decorative Home Statue
https://deodap.in/cdn/shop/files/v1yfZyfC4A.jpg?v=1776684099	https://deodap.in/cdn/shop/files/CnXOPI5mBr.jpg?v=1776684099	https://deodap.in/products/motivational-water-bottle-with-time-marker-leakproof-gym-bottle	Motivational Water Bottle with Time Marker Leakproof Gym Bottle	Rs. 258.00	Rs. 516.00	50% OFF	No reviews	Motivational Water Bottle with Time Marker Leakproof Gym...	Decrease quantity for Motivational Water Bottle with Time Marker Leakproof Gym Bottle
https://deodap.in/cdn/shop/files/E2r9NoKtfS.jpg?v=1776684093	https://deodap.in/cdn/shop/files/UhuAkhS0Bn.jpg?v=1776684093	https://deodap.in/products/cute-monk-covering-ears-showpiece-baby-figurine-for-desk-decor	Cute Monk Covering Ears Showpiece Baby Figurine for Desk Decor	Rs. 92.00	Rs. 184.00	50% OFF	No reviews	Cute Monk Covering Ears Showpiece Baby Figurine for...	Decrease quantity for Cute Monk Covering Ears Showpiece Baby Figurine for Desk Decor
https://deodap.in/cdn/shop/files/aKKphAGjBC.jpg?v=1776684093	https://deodap.in/cdn/shop/files/fPOUEMl8ug.jpg?v=1776684093	https://deodap.in/products/abstract-face-showpiece-statue-for-home-and-office-decor	Abstract Face Showpiece Statue for Home and Office Decor	Rs. 638.00	Rs. 1,276.00	50% OFF	No reviews	Abstract Face Showpiece Statue for Home and Office...	Decrease quantity for Abstract Face Showpiece Statue for Home and Office Decor
https://deodap.in/cdn/shop/files/gR26j11n3c.jpg?v=1776684093	https://deodap.in/cdn/shop/files/RC61sx3t88.jpg?v=1776684093	https://deodap.in/products/rabbit-couple-showpiece-for-home-decor-with-gold-accents	Rabbit Couple Showpiece for Home Decor with Gold Accents	Rs. 784.00	Rs. 1,568.00	50% OFF	No reviews	Rabbit Couple Showpiece for Home Decor with Gold...	Decrease quantity for Rabbit Couple Showpiece for Home Decor with Gold Accents
https://deodap.in/cdn/shop/files/gvPb2qwpOh.jpg?v=1776684093	https://deodap.in/cdn/shop/files/s49kDaz3QM.jpg?v=1776684093	https://deodap.in/products/white-gold-elephant-showpiece-decorative-home-statue	White Gold Elephant Showpiece Decorative Home Statue	Rs. 882.00	Rs. 1,764.00	50% OFF	No reviews	White Gold Elephant Showpiece Decorative Home Statue	Decrease quantity for White Gold Elephant Showpiece Decorative Home Statue
https://deodap.in/cdn/shop/files/no608saD6D.jpg?v=1776684093	https://deodap.in/cdn/shop/files/9EolJruj02.jpg?v=1776684093	https://deodap.in/products/smiling-monk-showpiece-cute-baby-buddha-desk-decor-figurine	Smiling Monk Showpiece Cute Baby Buddha Desk Decor Figurine	Rs. 92.00	Rs. 184.00	50% OFF	No reviews	Smiling Monk Showpiece Cute Baby Buddha Desk Decor...	Decrease quantity for Smiling Monk Showpiece Cute Baby Buddha Desk Decor Figurine
https://deodap.in/cdn/shop/files/mqXWcdbBny.jpg?v=1776684093	https://deodap.in/cdn/shop/files/dvlnT5vgG0.jpg?v=1776684093	https://deodap.in/products/abstract-face-showpiece-for-home-decor-table-display	Abstract Face Showpiece for Home Decor Table Display	Rs. 931.00	Rs. 1,862.00	50% OFF	No reviews	Abstract Face Showpiece for Home Decor Table Display	Decrease quantity for Abstract Face Showpiece for Home Decor Table Display
https://deodap.in/cdn/shop/files/27HP1MSzXb.jpg?v=1776684093	https://deodap.in/cdn/shop/files/LJ8j0GB0ef.jpg?v=1776684093	https://deodap.in/products/golden-cow-with-calf-showpiece-decorative-idol-for-home-decor	Golden Cow with Calf Showpiece Decorative Idol for Home Decor	Rs. 394.00	Rs. 788.00	50% OFF	No reviews	Golden Cow with Calf Showpiece Decorative Idol for...	Decrease quantity for Golden Cow with Calf Showpiece Decorative Idol for Home Decor
https://deodap.in/cdn/shop/files/dogg6YKI9J.jpg?v=1776684093	https://deodap.in/cdn/shop/files/4I7tykP94M.jpg?v=1776684093	https://deodap.in/products/heart-shape-wooden-photo-frame-lamp-with-led-crystal-light	Heart Shape Wooden Photo Frame Lamp with LED Crystal Light	Rs. 264.00	Rs. 528.00	50% OFF	No reviews	Heart Shape Wooden Photo Frame Lamp with LED...	Decrease quantity for Heart Shape Wooden Photo Frame Lamp with LED Crystal Light
https://deodap.in/cdn/shop/files/Kj6LPaIB7g.jpg?v=1776684093	https://deodap.in/cdn/shop/files/3iFKEA1LhU.jpg?v=1776684093	https://deodap.in/products/abstract-praying-lady-sculpture-decorative-home-showpiece	Abstract Praying Lady Sculpture Decorative Home Showpiece	Rs. 771.00	Rs. 1,542.00	50% OFF	No reviews	Abstract Praying Lady Sculpture Decorative Home Showpiece	Decrease quantity for Abstract Praying Lady Sculpture Decorative Home Showpiece
https://deodap.in/cdn/shop/files/E3cSKa3zpR.jpg?v=1776684093	https://deodap.in/cdn/shop/files/Uf8Ap9Wqv6.jpg?v=1776684093	https://deodap.in/products/modern-elephant-showpiece-for-home-decor-with-matte-finish	Modern Elephant Showpiece for Home Decor with Matte Finish	Rs. 810.00	Rs. 1,620.00	50% OFF	No reviews	Modern Elephant Showpiece for Home Decor with Matte...	Decrease quantity for Modern Elephant Showpiece for Home Decor with Matte Finish
https://deodap.in/cdn/shop/files/ds7u8hsX59.jpg?v=1776684093	https://deodap.in/cdn/shop/files/WzDjvoaM9p.jpg?v=1776684093	https://deodap.in/products/cute-monk-showpiece-laughing-baby-figurine-for-home-desk-decor	Cute Monk Showpiece Laughing Baby Figurine for Home & Desk Decor	Rs. 92.00	Rs. 184.00	50% OFF	No reviews	Cute Monk Showpiece Laughing Baby Figurine for Home...	Decrease quantity for Cute Monk Showpiece Laughing Baby Figurine for Home &amp; Desk Decor
https://deodap.in/cdn/shop/files/aZFHKTtOTX.jpg?v=1776684093	https://deodap.in/cdn/shop/files/GfJkApvh9Y.jpg?v=1776684093	https://deodap.in/products/elegant-elephant-showpiece-for-home-decor-with-modern-design	Elegant Elephant Showpiece for Home Decor with Modern Design	Rs. 810.00	Rs. 1,620.00	50% OFF	No reviews	Elegant Elephant Showpiece for Home Decor with Modern...	Decrease quantity for Elegant Elephant Showpiece for Home Decor with Modern Design
https://deodap.in/cdn/shop/files/mLnAeWu9wR.jpg?v=1776684093	https://deodap.in/cdn/shop/files/ycAeETVtPm.jpg?v=1776684093	https://deodap.in/products/pastel-deer-showpiece-set-with-golden-antlers-for-home-decor	Pastel Deer Showpiece Set with Golden Antlers for Home Decor	Rs. 970.00	Rs. 1,940.00	50% OFF	No reviews	Pastel Deer Showpiece Set with Golden Antlers for...	Decrease quantity for Pastel Deer Showpiece Set with Golden Antlers for Home Decor
https://deodap.in/cdn/shop/files/DGwtcl6hGY.jpg?v=1776684093	https://deodap.in/cdn/shop/files/MTXOoMMJg5.jpg?v=1776684093	https://deodap.in/products/wooden-led-photo-frame-lamp-with-crystal-light-base	Wooden LED Photo Frame Lamp with Crystal Light Base	Rs. 264.00	Rs. 528.00	50% OFF	No reviews	Wooden LED Photo Frame Lamp with Crystal Light...	Decrease quantity for Wooden LED Photo Frame Lamp with Crystal Light Base
https://deodap.in/cdn/shop/files/wall-steaker_4_-1_8faf01cc-d86a-4dea-8d4f-56157bc19a60.jpg?v=1776680043	https://deodap.in/cdn/shop/files/16035_1.jpg?v=1776680043	https://deodap.in/products/self-adhesive-3d-foam-wall-panel-cushion-wallpaper-1-pc-brown-69x35-cm	self adhesive 3d foam wall panel brown	Rs. 84.00	Rs. 299.00	71% OFF	No reviews	Self Adhesive 3D Foam Wall Panel Cushion Wallpaper...	Decrease quantity for Self Adhesive 3D Foam Wall Panel Cushion Wallpaper (1 Pc, Brown, 69x35 Cm)
https://deodap.in/cdn/shop/files/wall-steaker-1.jpg?v=1776680331	https://deodap.in/cdn/shop/files/sku_8d65f2a4-90f3-445f-b083-5c83578b3fe6.jpg?v=1776680331	https://deodap.in/products/self-adhesive-3d-foam-wall-panel-cushion-wallpaper-1-pc-white-69x35-cm	self adhesive 3d foam wall panel white	Rs. 84.00	Rs. 299.00	71% OFF	No reviews	Self Adhesive 3D Foam Wall Panel Cushion Wallpaper...	Decrease quantity for Self Adhesive 3D Foam Wall Panel Cushion Wallpaper (1 Pc, White, 69x35 Cm)
https://deodap.in/cdn/shop/files/wall-steaker_2_-1.jpg?v=1776680330	https://deodap.in/cdn/shop/files/sku_140b444f-8dc0-4182-ae30-5661b7a2f445.jpg?v=1776680330	https://deodap.in/products/self-adhesive-3d-foam-wall-panel-cushion-wallpaper-1-pc-pink-69x35-cm	self adhesive 3d foam wall panel pink	Rs. 84.00	Rs. 299.00	71% OFF	No reviews	Self Adhesive 3D Foam Wall Panel Cushion Wallpaper...	Decrease quantity for Self Adhesive 3D Foam Wall Panel Cushion Wallpaper (1 Pc, Pink, 69x35 Cm)
https://deodap.in/cdn/shop/files/wall-steaker_3_-1.jpg?v=1776678435	https://deodap.in/cdn/shop/files/sku_25101207-900a-499f-88d6-c5bedeb09b54.jpg?v=1776678435	https://deodap.in/products/self-adhesive-3d-foam-wall-panel-cushion-wallpaper-1-pc-blue-69x35-cm	self adhesive 3d foam wall panel blue	Rs. 84.00	Rs. 299.00	71% OFF	No reviews	Self Adhesive 3D Foam Wall Panel Cushion Wallpaper...	Decrease quantity for Self Adhesive 3D Foam Wall Panel Cushion Wallpaper (1 Pc, Blue, 69x35 Cm)
https://deodap.in/cdn/shop/files/Coin-Purse-01.jpg?v=1762921966	https://deodap.in/cdn/shop/files/WhatsAppImage2025-11-11at16.07.38_1.jpg?v=1762921966	https://deodap.in/products/premium-foldable-pu-leather-coin-pouch-1-pc-copy	Premium Foldable PU Leather Coin Pouch (1 Pc)	Rs. 28.71	Rs. 99.00	71% OFF	No reviews	Premium Foldable PU Leather Coin Pouch (1 Pc)	Decrease quantity for Premium Foldable PU Leather Coin Pouch (1 Pc)
https://deodap.in/cdn/shop/files/Glass-Sand-Timer-1.jpg?v=1776331298	https://deodap.in/cdn/shop/files/sku_779aff7e-f3f4-437a-8db6-02e462782a6c.jpg?v=1776331395	https://deodap.in/products/4-minute-approx-sand-timer-hourglass-decorative-glass-timer-1-pc-copy	4-Minute approx Sand Timer Hourglass – Decorative Glass Timer (1 Pc)	Rs. 96.00	Rs. 299.00	67% OFF	(44)	4-Minute approx Sand Timer Hourglass – Decorative Glass...	Decrease quantity for 4-Minute approx Sand Timer Hourglass – Decorative Glass Timer (1 Pc)
https://deodap.in/cdn/shop/files/Paper-Lanterns-1.jpg?v=1776327802	https://deodap.in/cdn/shop/files/sku_4464162d-1da9-46cf-8e53-e76e22cb154f.jpg?v=1776327923	https://deodap.in/products/diy-paper-lantern-craft-kit-decorative-hanging-lantern-set-copy	DIY Paper Lantern Craft Kit Decorative Hanging Lantern Set	Rs. 44.00	Rs. 299.00	85% OFF	(22)	DIY Paper Lantern Craft Kit Decorative Hanging Lantern...	Decrease quantity for DIY Paper Lantern Craft Kit Decorative Hanging Lantern Set
https://deodap.in/cdn/shop/files/01_4f7a5f3a-4008-42d8-900f-df8034f8d179.jpg?v=1737615083	https://deodap.in/cdn/shop/files/115_d3ee9869-843e-4c99-ac99-a304487466ad.jpg?v=1737615083	https://deodap.in/products/silicone-oil-brush-pastry-brush-oil-cooking-brush-1-pc-copy	SilicoSwipe	Rs. 51.00	Rs. 199.00	74% OFF	No reviews	Silicone Oil brush, Pastry Brush, Oil Cooking Brush...	Decrease quantity for Silicone Oil brush, Pastry Brush, Oil Cooking Brush (1 Pc)
https://deodap.in/cdn/shop/files/MiniLemonCitrusPresser-WOSKU-01.jpg?v=1762839015	https://deodap.in/cdn/shop/files/99b7dc07-2629-4e1b-bdae-48abae062be4.jpg?v=1762839015	https://deodap.in/products/hand-operated-citrus-juicer-1-pc-copy	Storage Box	Rs. 28.71	Rs. 99.00	71% OFF	No reviews	Hand-Operated Citrus Juicer (1 Pc)	Decrease quantity for Hand-Operated Citrus Juicer (1 Pc)
https://deodap.in/cdn/shop/files/Sf0aTdp06l.jpg?v=1776662312	https://deodap.in/cdn/shop/files/fxB09hloFG.jpg?v=1776662312	https://deodap.in/products/multi-color-fish-shape-vegetable-peeler-with-sharp-stainless-steel-blade-tool-pack-of-3	Multi Color Fish Shape Vegetable Peeler with Sharp Stainless Steel Blade Tool (Pack Of 3)	Rs. 36.00	Rs. 149.00	75% OFF	No reviews	Multi Color Fish Shape Vegetable Peeler with Sharp...	Decrease quantity for Multi Color Fish Shape Vegetable Peeler with Sharp Stainless Steel Blade Tool (Pack Of 3)
https://deodap.in/cdn/shop/files/e9aAEtD2z4.jpg?v=1776516298	https://deodap.in/cdn/shop/files/1Elb2YLNt2.jpg?v=1776516298	https://deodap.in/products/handcrafted-blue-metal-tractor-toy-small	Handcrafted Blue Metal Tractor Toy Small	Rs. 186.00	Rs. 450.00	58% OFF	No reviews	Handcrafted Blue Metal Tractor Toy Small	Decrease quantity for Handcrafted Blue Metal Tractor Toy Small
https://deodap.in/cdn/shop/files/G2hr4HHh2q.jpg?v=1776516298	https://deodap.in/cdn/shop/files/7QyrLKsSAJ.png?v=1776516298	https://deodap.in/products/handcrafted-blue-metal-tractor-toy-big	Handcrafted Blue Metal Tractor Toy Big	Rs. 264.00	Rs. 500.00	47% OFF	No reviews	Handcrafted Blue Metal Tractor Toy Big	Decrease quantity for Handcrafted Blue Metal Tractor Toy Big
https://deodap.in/cdn/shop/files/Z5DyQenRlL.png?v=1776516298	https://deodap.in/cdn/shop/files/aCbjuChcee.png?v=1776516298	https://deodap.in/products/handcrafted-metal-indian-cargo-tricycle	Handcrafted Metal Indian Cargo Tricycle	Rs. 264.00	Rs. 600.00	56% OFF	No reviews	Handcrafted Metal Indian Cargo Tricycle	Decrease quantity for Handcrafted Metal Indian Cargo Tricycle
https://deodap.in/cdn/shop/files/GsvgFaZUi6.jpg?v=1776515149	https://deodap.in/cdn/shop/files/zXhzFA5izd.jpg?v=1776515148	https://deodap.in/products/rajwadi-temple-gate-pendant-with-pink-leaf-emerald-drops-long-double-strand-mangalsutra	Rajwadi Temple Gate Pendant with Pink Leaf & Emerald Drops Long Double Strand Mangalsutra	Rs. 164.00	Rs. 328.00	50% OFF	No reviews	Rajwadi Temple Gate Pendant with Pink Leaf &...	Decrease quantity for Rajwadi Temple Gate Pendant with Pink Leaf &amp; Emerald Drops Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/27bbgkRz4K.jpg?v=1776515149	https://deodap.in/cdn/shop/files/5yXK1spct6.jpg?v=1776515149	https://deodap.in/products/antique-finish-sunburst-filigree-pendant-with-rainbow-bead-cascade-double-strand-mangalsutra	Antique Finish Sunburst Filigree Pendant with Rainbow Bead Cascade Double Strand Mangalsutra	Rs. 130.00	Rs. 260.00	50% OFF	No reviews	Antique Finish Sunburst Filigree Pendant with Rainbow Bea...	Decrease quantity for Antique Finish Sunburst Filigree Pendant with Rainbow Bead Cascade Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/GLKSwdPnsj.jpg?v=1776515148	https://deodap.in/cdn/shop/files/Md6KE4MpuJ.jpg?v=1776515149	https://deodap.in/products/antique-finish-shiva-linga-inspired-cylinder-pendant-double-strand-mangalsutra	Antique Finish Shiva Linga Inspired Cylinder Pendant Double Strand Mangalsutra	Rs. 84.00	Rs. 168.00	50% OFF	No reviews	Antique Finish Shiva Linga Inspired Cylinder Pendant Doub...	Decrease quantity for Antique Finish Shiva Linga Inspired Cylinder Pendant Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/XU99gMTuaW.jpg?v=1776515148	https://deodap.in/cdn/shop/files/9RhpyNgEjV.jpg?v=1776515149	https://deodap.in/products/antique-finish-radha-krishna-deity-oval-pendant-with-crescent-drop-earring-set-double-strand-mangalsutra	Antique Finish Radha Krishna Deity Oval Pendant with Crescent Drop Earring Set Double Strand Mangalsutra	Rs. 101.00	Rs. 202.00	50% OFF	No reviews	Antique Finish Radha Krishna Deity Oval Pendant with...	Decrease quantity for Antique Finish Radha Krishna Deity Oval Pendant with Crescent Drop Earring Set Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/QhGlhclvFY.jpg?v=1776515148	https://deodap.in/cdn/shop/files/Ji8mXDqwBj.jpg?v=1776515148	https://deodap.in/products/antique-finish-sun-wheel-pendant-with-multi-petal-enamel-double-strand-mangalsutra	Antique Finish Sun Wheel Pendant with Multi-Petal Enamel Double Strand Mangalsutra	Rs. 84.00	Rs. 168.00	50% OFF	No reviews	Antique Finish Sun Wheel Pendant with Multi-Petal Enamel...	Decrease quantity for Antique Finish Sun Wheel Pendant with Multi-Petal Enamel Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/74hTYtoXXn.jpg?v=1776515149	https://deodap.in/cdn/shop/files/XoAYomfsft.jpg?v=1776515149	https://deodap.in/products/antique-finish-crescent-paisley-pendant-with-ghungroo-drops-long-single-strand-mangalsutra	Antique Finish Crescent Paisley Pendant with Ghungroo Drops Long Single Strand Mangalsutra	Rs. 68.00	Rs. 136.00	50% OFF	No reviews	Antique Finish Crescent Paisley Pendant with Ghungroo Dro...	Decrease quantity for Antique Finish Crescent Paisley Pendant with Ghungroo Drops Long Single Strand Mangalsutra
https://deodap.in/cdn/shop/files/G6hCyDDFHo.jpg?v=1776515148	https://deodap.in/cdn/shop/files/tAkOyDul0q.jpg?v=1776515148	https://deodap.in/products/rose-gold-finish-marquise-eye-cz-pendant-with-v-frame-double-strand-mangalsutra	Rose Gold Finish Marquise Eye CZ Pendant with V-Frame Double Strand Mangalsutra	Rs. 96.00	Rs. 192.00	50% OFF	No reviews	Rose Gold Finish Marquise Eye CZ Pendant with...	Decrease quantity for Rose Gold Finish Marquise Eye CZ Pendant with V-Frame Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/STEeLDKxTd.jpg?v=1776515149	https://deodap.in/cdn/shop/files/7HgG0jylEw.jpg?v=1776515149	https://deodap.in/products/antique-finish-meenakari-floral-fan-pendant-short-single-strand-mangalsutra	Antique Finish Meenakari Floral Fan Pendant Short Single Strand Mangalsutra	Rs. 68.00	Rs. 136.00	50% OFF	No reviews	Antique Finish Meenakari Floral Fan Pendant Short Single...	Decrease quantity for Antique Finish Meenakari Floral Fan Pendant Short Single Strand Mangalsutra
https://deodap.in/cdn/shop/files/3iP9Y1SQAG.jpg?v=1776515149	https://deodap.in/cdn/shop/files/3D4j3381TZ.jpg?v=1776515148	https://deodap.in/products/antique-finish-half-moon-chandrakor-pendant-with-ghungroo-double-strand-mangalsutra	Antique Finish Half Moon Chandrakor Pendant with Ghungroo Double Strand Mangalsutra	Rs. 84.00	Rs. 168.00	50% OFF	No reviews	Antique Finish Half Moon Chandrakor Pendant with Ghungroo...	Decrease quantity for Antique Finish Half Moon Chandrakor Pendant with Ghungroo Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/a0sFueGpTu.jpg?v=1776515149	https://deodap.in/cdn/shop/files/Sxk6ESj8o8.jpg?v=1776515149	https://deodap.in/products/mirrored-twin-peacock-pendant-with-pastel-drop-long-double-strand-mangalsutra	Mirrored Twin Peacock Pendant with Pastel Drop Long Double Strand Mangalsutra	Rs. 130.00	Rs. 260.00	50% OFF	No reviews	Mirrored Twin Peacock Pendant with Pastel Drop Long...	Decrease quantity for Mirrored Twin Peacock Pendant with Pastel Drop Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/xBhBG2pyb3.jpg?v=1776515148	https://deodap.in/cdn/shop/files/IFtzcXusFn.jpg?v=1776515149	https://deodap.in/products/crescent-wing-filigree-pendant-with-pink-enamel-wings-heart-locket-long-double-strand-mangalsutra	Crescent Wing Filigree Pendant with Pink Enamel Wings & Heart Locket Long Double Strand Mangalsutra	Rs. 164.00	Rs. 328.00	50% OFF	No reviews	Crescent Wing Filigree Pendant with Pink Enamel Wings...	Decrease quantity for Crescent Wing Filigree Pendant with Pink Enamel Wings &amp; Heart Locket Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/kbsor33kkA.jpg?v=1776515149	https://deodap.in/cdn/shop/files/WYLxMHleUd.jpg?v=1776515149	https://deodap.in/products/tortoise-shell-temple-pendant-with-emerald-crown-cz-crescent-double-strand-mangalsutra	Tortoise Shell Temple Pendant with Emerald Crown & CZ Crescent Double Strand Mangalsutra	Rs. 130.00	Rs. 260.00	50% OFF	No reviews	Tortoise Shell Temple Pendant with Emerald Crown &...	Decrease quantity for Tortoise Shell Temple Pendant with Emerald Crown &amp; CZ Crescent Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/VH8ynLZ1Z8.jpg?v=1776515149	https://deodap.in/cdn/shop/files/FsEKCL4ApV.jpg?v=1776515148	https://deodap.in/products/antique-finish-kalash-pot-pendant-with-green-pink-enamel-double-strand-mangalsutra	Antique Finish Kalash Pot Pendant with Green & Pink Enamel Double Strand Mangalsutra	Rs. 84.00	Rs. 168.00	50% OFF	No reviews	Antique Finish Kalash Pot Pendant with Green &...	Decrease quantity for Antique Finish Kalash Pot Pendant with Green &amp; Pink Enamel Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/CpiOGRaNRC.jpg?v=1776515148	https://deodap.in/cdn/shop/files/1zCeTubP0P.jpg?v=1776515149	https://deodap.in/products/antique-finish-sunburst-peacock-pendant-with-ghungroo-emerald-drop-double-strand-mangalsutra	Antique Finish Sunburst Peacock Pendant with Ghungroo & Emerald Drop Double Strand Mangalsutra	Rs. 84.00	Rs. 168.00	50% OFF	No reviews	Antique Finish Sunburst Peacock Pendant with Ghungroo &am...	Decrease quantity for Antique Finish Sunburst Peacock Pendant with Ghungroo &amp; Emerald Drop Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/7hAc4bnZC3.jpg?v=1776515148	https://deodap.in/cdn/shop/files/Rpp3IfXPbL.jpg?v=1776515148	https://deodap.in/products/rose-gold-finish-full-cz-butterfly-wing-pendant-double-strand-mangalsutra	Rose Gold Finish Full CZ Butterfly Wing Pendant Double Strand Mangalsutra	Rs. 96.00	Rs. 192.00	50% OFF	No reviews	Rose Gold Finish Full CZ Butterfly Wing Pendant...	Decrease quantity for Rose Gold Finish Full CZ Butterfly Wing Pendant Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/1wJ8fA9zNs.jpg?v=1776515149	https://deodap.in/cdn/shop/files/Jbu1Kk4vcJ.jpg?v=1776515149	https://deodap.in/products/antique-finish-lotus-peacock-fan-pendant-with-multi-petal-enamel-extra-long-double-strand-mangalsutra	Antique Finish Lotus Peacock Fan Pendant with Multi-Petal Enamel Extra Long Double Strand Mangalsutra	Rs. 130.00	Rs. 260.00	50% OFF	No reviews	Antique Finish Lotus Peacock Fan Pendant with Multi-Petal...	Decrease quantity for Antique Finish Lotus Peacock Fan Pendant with Multi-Petal Enamel Extra Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/LB4QTej33b.jpg?v=1776515148	https://deodap.in/cdn/shop/files/JNtKIcmhM9.jpg?v=1776515149	https://deodap.in/products/rose-gold-finish-openwork-floral-petal-cz-pendant-double-strand-mangalsutra	Rose Gold Finish Openwork Floral Petal CZ Pendant Double Strand Mangalsutra	Rs. 96.00	Rs. 192.00	50% OFF	No reviews	Rose Gold Finish Openwork Floral Petal CZ Pendant...	Decrease quantity for Rose Gold Finish Openwork Floral Petal CZ Pendant Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/yb17Vy6l8V.jpg?v=1776515149	https://deodap.in/cdn/shop/files/Qk10PBbY2l.jpg?v=1776515148	https://deodap.in/products/rose-gold-finish-wave-arc-cz-pendant-with-pear-drop-double-strand-mangalsutra	Rose Gold Finish Wave Arc CZ Pendant with Pear Drop Double Strand Mangalsutra	Rs. 73.00	Rs. 146.00	50% OFF	No reviews	Rose Gold Finish Wave Arc CZ Pendant with...	Decrease quantity for Rose Gold Finish Wave Arc CZ Pendant with Pear Drop Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/Sgm3WUTLMW.jpg?v=1776515149	https://deodap.in/cdn/shop/files/CfykJvhpW3.jpg?v=1776515148	https://deodap.in/products/antique-finish-floral-crown-lotus-pendant-with-pink-enamel-petals-long-double-strand-mangalsutra	Antique Finish Floral Crown Lotus Pendant with Pink Enamel Petals Long Double Strand Mangalsutra	Rs. 164.00	Rs. 328.00	50% OFF	No reviews	Antique Finish Floral Crown Lotus Pendant with Pink...	Decrease quantity for Antique Finish Floral Crown Lotus Pendant with Pink Enamel Petals Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/2JfUvO7RMd.jpg?v=1776515148	https://deodap.in/cdn/shop/files/uM4zOcmrjI.jpg?v=1776515148	https://deodap.in/products/antique-finish-lotus-medallion-with-turquoise-drops-ruby-stone-single-strand-mangalsutra	Antique Finish Lotus Medallion with Turquoise Drops & Ruby Stone Single Strand Mangalsutra	Rs. 68.00	Rs. 136.00	50% OFF	No reviews	Antique Finish Lotus Medallion with Turquoise Drops &...	Decrease quantity for Antique Finish Lotus Medallion with Turquoise Drops &amp; Ruby Stone Single Strand Mangalsutra
https://deodap.in/cdn/shop/files/vva1DH3AsT.jpg?v=1776515148	https://deodap.in/cdn/shop/files/jvzJIfBQi1.jpg?v=1776515148	https://deodap.in/products/antique-finish-makara-dragon-scroll-pendant-with-fan-enamel-base-long-double-strand-mangalsutra	Antique Finish Makara Dragon Scroll Pendant with Fan Enamel Base Long Double Strand Mangalsutra	Rs. 164.00	Rs. 328.00	50% OFF	No reviews	Antique Finish Makara Dragon Scroll Pendant with Fan...	Decrease quantity for Antique Finish Makara Dragon Scroll Pendant with Fan Enamel Base Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/R56fEjawLn.jpg?v=1776515148	https://deodap.in/cdn/shop/files/ql3DcFtqfF.jpg?v=1776515148	https://deodap.in/products/antique-finish-radha-krishna-deity-medallion-with-teal-enamel-drop-earring-set-double-strand-mangalsutra	Antique Finish Radha Krishna Deity Medallion with Teal Enamel Drop Earring Set Double Strand Mangalsutra	Rs. 101.00	Rs. 202.00	50% OFF	No reviews	Antique Finish Radha Krishna Deity Medallion with Teal...	Decrease quantity for Antique Finish Radha Krishna Deity Medallion with Teal Enamel Drop Earring Set Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/DsvA8eDrX0.jpg?v=1776515149	https://deodap.in/cdn/shop/files/0x5JS6LIjP.jpg?v=1776515149	https://deodap.in/products/rose-gold-finish-triple-strand-heart-charms-cz-bar-mangalsutra-with-teardrop-drop	Rose Gold Finish Triple Strand Heart Charms & CZ Bar Mangalsutra with Teardrop Drop	Rs. 73.00	Rs. 146.00	50% OFF	No reviews	Rose Gold Finish Triple Strand Heart Charms &...	Decrease quantity for Rose Gold Finish Triple Strand Heart Charms &amp; CZ Bar Mangalsutra with Teardrop Drop
https://deodap.in/cdn/shop/files/00GVd5mE1U.jpg?v=1776515148	https://deodap.in/cdn/shop/files/WNZFYUwXzG.jpg?v=1776515148	https://deodap.in/products/antique-finish-navaratna-peacock-feather-fan-with-multi-stone-rows-extra-long-double-strand-mangalsutra	Antique Finish Navaratna Peacock Feather Fan with Multi-Stone Rows Extra Long Double Strand Mangalsutra	Rs. 130.00	Rs. 260.00	50% OFF	No reviews	Antique Finish Navaratna Peacock Feather Fan with Multi-S...	Decrease quantity for Antique Finish Navaratna Peacock Feather Fan with Multi-Stone Rows Extra Long Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/GXKjArbXHD.jpg?v=1776515148	https://deodap.in/cdn/shop/files/0LSnKmr542.jpg?v=1776515149	https://deodap.in/products/rose-gold-finish-heart-wheat-leaf-v-drop-cz-pendant-mangalsutra	Rose Gold Finish Heart & Wheat Leaf V-Drop CZ Pendant Mangalsutra	Rs. 47.00	Rs. 94.00	50% OFF	No reviews	Rose Gold Finish Heart & Wheat Leaf V-Drop...	Decrease quantity for Rose Gold Finish Heart &amp; Wheat Leaf V-Drop CZ Pendant Mangalsutra
https://deodap.in/cdn/shop/files/Ou3ehZIIFK.jpg?v=1776515148	https://deodap.in/cdn/shop/files/bqkQ0TjJKc.jpg?v=1776515149	https://deodap.in/products/antique-finish-grand-meenakari-pendant-with-teardrop-drop-long-single-strand-mangalsutra	Antique Finish Grand Meenakari Pendant with Teardrop Drop Long Single Strand Mangalsutra	Rs. 68.00	Rs. 136.00	50% OFF	No reviews	Antique Finish Grand Meenakari Pendant with Teardrop Drop...	Decrease quantity for Antique Finish Grand Meenakari Pendant with Teardrop Drop Long Single Strand Mangalsutra
https://deodap.in/cdn/shop/files/PcjOew3O1M.jpg?v=1776515149	https://deodap.in/cdn/shop/files/FWKCplZtlr.jpg?v=1776515149	https://deodap.in/products/antique-finish-circular-medallion-with-pink-enamel-flowers-ruby-centre-mangalsutra	Antique Finish Circular Medallion with Pink Enamel Flowers & Ruby Centre Mangalsutra	Rs. 68.00	Rs. 136.00	50% OFF	No reviews	Antique Finish Circular Medallion with Pink Enamel Flower...	Decrease quantity for Antique Finish Circular Medallion with Pink Enamel Flowers &amp; Ruby Centre Mangalsutra
https://deodap.in/cdn/shop/files/wrOIty00WZ.jpg?v=1776515149	https://deodap.in/cdn/shop/files/9s0U6N4mta.jpg?v=1776515149	https://deodap.in/products/rose-gold-finish-cascading-leaf-spray-cz-pendant-double-strand-mangalsutra	Rose Gold Finish Cascading Leaf Spray CZ Pendant Double Strand Mangalsutra	Rs. 73.00	Rs. 146.00	50% OFF	No reviews	Rose Gold Finish Cascading Leaf Spray CZ Pendant...	Decrease quantity for Rose Gold Finish Cascading Leaf Spray CZ Pendant Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/IjyXeRwoD9.jpg?v=1776515149	https://deodap.in/cdn/shop/files/2GXdhYX3xb.jpg?v=1776515149	https://deodap.in/products/rose-gold-finish-triple-starburst-cz-cluster-pendant-double-strand-mangalsutra	Rose Gold Finish Triple Starburst CZ Cluster Pendant Double Strand Mangalsutra	Rs. 96.00	Rs. 192.00	50% OFF	No reviews	Rose Gold Finish Triple Starburst CZ Cluster Pendant...	Decrease quantity for Rose Gold Finish Triple Starburst CZ Cluster Pendant Double Strand Mangalsutra
https://deodap.in/cdn/shop/files/0u1OTZ8dfR.jpg?v=1776515148	https://deodap.in/cdn/shop/files/7japdChL6b.jpg?v=1776515149	https://deodap.in/products/rose-gold-finish-full-cz-crescent-moon-bar-double-strand-mangalsutra	Rose Gold Finish Full CZ Crescent Moon Bar Double Strand Mangalsutra	Rs. 96.00	Rs. 192.00	50% OFF	No reviews	Rose Gold Finish Full CZ Crescent Moon Bar...	Decrease quantity for Rose Gold Finish Full CZ Crescent Moon Bar Double Strand Mangalsutra`;

const lines = rawData.trim().split('\n').slice(1);
const products = lines.map((line, idx) => {
    const parts = line.split('\t');
    const image = parts[0];
    const title = parts[3]; // It's in the 4th column
    const rawPrice = parts[4].replace('Rs. ', '').replace(/,/g, '');
    const rawOldPrice = parts[5].replace('Rs. ', '').replace(/,/g, '');
    let price = parseFloat(rawPrice);
    let oldPrice = parseFloat(rawOldPrice);
    
    // Add 20% extra price
    price = Math.ceil(price * 1.2);
    oldPrice = Math.ceil(oldPrice * 1.2);

    let category = "Essentials";
    const tl = title.toLowerCase();
    if(tl.includes("watch")) {
        category = "Men Clothing";
    } else if(tl.includes("mangalsutra") || tl.includes("pendant")) {
        category = "Women Clothing";
    } else if(tl.includes("toy") || tl.includes("lamp") || tl.includes("figurine") || tl.includes("showpiece")) {
        category = "Essentials";
    }

    return {
        id: "p_" + Date.now() + "_" + idx,
        title: title,
        price,
        oldPrice,
        category,
        image,
        shortDescription: title + " - Top quality drop-shipped product.",
        description: "Premium product directly sourced for you. Designed for durability, elegance, and incredible value.",
        isNew: idx < 8
    }
});

let out = `export interface Product {
  id: string;
  title: string;
  price: number;
  oldPrice: number;
  category: string;
  image: string;
  shortDescription: string;
  description?: string;
  isNew?: boolean;
}

export const products: Product[] = ${JSON.stringify(products, null, 2)};

export const getProductsByCategory = (category: string) => {
  if (category === "All") return products;
  return products.filter(p => p.category === category);
};

export const categories = ["All", "Men Clothing", "Women Clothing", "Electronics", "Essentials"];
`;

fs.writeFileSync(path.join(process.cwd(), 'src/data/products.ts'), out);
console.log('Update complete on ' + process.cwd());
